export enum CalculationBatchTypes {
  // Delivery = 3,
  // FebProgress = 4,
  // MayProgress = 5,
  // FinalPayment = 6,
  // SpotEMF = 10,
  // Deferral = 11,
  // YearEnd = 12,
  // TrueUp = 13
  Delivery = 3,
  FebProgress = 4,
  MayProgress = 5,
  FinalPayment = 6,
  TrueUp = 7,
  SpotEMF = 10,
  Deferral = 11,
  DeliveryProgression = 13,
  YearEnd = 14,
  December = 15,
}
